spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/risk
  username: risk
  password: risk
  driverClassName: org.postgresql.Driver

 jpa:
  database: POSTGRESQL
  show-sql: true
  hibernate:
   ddl-auto: create-drop
   dialect: org.hibernate.dialect.PostgreSQLDialect
   naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy